# Generated by Django 6.0.4 on 2026-04-24 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('employee_card_id', models.BigIntegerField(unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='locations.site')),
            ],
            options={
                'db_table': 'Employees',
                'permissions': [('transfer_employee', 'Can transfer an employee to a different site or department')],
            },
        ),
    ]
