# Generated by Django 5.2.7 on 2026-05-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('transfer_employee', 'Can transfer an employee to a different site or department'), ('print_acknowledgment', 'Can print employee asset acknowledgment forms')]},
        ),
    ]
