# Generated by Django 5.2.7 on 2026-05-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('print_acknowledgment', 'Can print employee asset acknowledgment forms')]},
        ),
    ]
