# Generated by Django 5.2.7 on 2026-05-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('print_acknowledgment', 'Can print employee asset acknowledgment forms'), ('export_employee', 'Can export employee data to a file')]},
        ),
    ]
