# Generated by Django 6.0.4 on 2026-05-01 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('assign_role_user', 'Can assign roles to users'), ('reset_password_user', "Can reset another user's password"), ('activate_user', 'Can activate or deactivate users')]},
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_sites',
            field=models.ManyToManyField(blank=True, help_text='Used when site scope is "Specific Branches".', related_name='allowed_users', to='locations.site', verbose_name='Allowed Sites'),
        ),
        migrations.AddField(
            model_name='user',
            name='own_site',
            field=models.ForeignKey(blank=True, help_text='Used when site scope is "Own Branch Only".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_users', to='locations.site', verbose_name='Own Site'),
        ),
        migrations.AddField(
            model_name='user',
            name='site_scope',
            field=models.CharField(choices=[('all', 'All Branches'), ('own', 'Own Branch Only'), ('specific', 'Specific Branches')], default='own', max_length=10, verbose_name='Site Scope'),
        ),
    ]
