# Generated by Django 5.2.7 on 2026-05-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('policy', models.TextField(blank=True, help_text='Acknowledgment policy text printed on receipt forms.')),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'db_table': 'CompanyProfile',
            },
        ),
    ]
