# Generated by Django 6.0.4 on 2026-05-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_allowed_sites_user_own_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('reset_password_user', "Can reset another user's password"), ('activate_user', 'Can activate or deactivate users')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
