# Generated by Django 6.0.4 on 2026-04-24 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_accessory_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Accessory_Types',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpus', to='inventory.brand')),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_cpus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CPUs',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('flag', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('lost', 'Lost'), ('retired', 'Retired'), ('under_maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('ram_size_gb', models.PositiveSmallIntegerField(blank=True, help_text='RAM in GB', null=True)),
                ('hdd_storage_gb', models.PositiveIntegerField(blank=True, help_text='HDD in GB', null=True)),
                ('ssd_storage_gb', models.PositiveIntegerField(blank=True, help_text='SSD in GB', null=True)),
                ('screen_size_inch', models.FloatField(blank=True, help_text='Screen size in inches', null=True)),
                ('ports_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.brand')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.cpu')),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_devices', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='locations.site')),
            ],
            options={
                'db_table': 'Devices',
                'permissions': [('retire_device', 'Can mark a device as Retired'), ('flag_device', 'Can change the status flag of a device'), ('toggle_maintenance', 'Can toggle maintenance mode on a device'), ('view_device_specs', 'Can view detailed hardware specifications')],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('flag', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('lost', 'Lost'), ('retired', 'Retired'), ('under_maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_accessories', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='locations.site')),
                ('accessory_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='inventory.accessorytype')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='inventory.brand')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='inventory.device')),
            ],
            options={
                'db_table': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_device_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Devices_Categories',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.devicecategory'),
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_models', to='inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_models', to='inventory.devicecategory')),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_device_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Devices_Models',
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.devicemodel'),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gpus', to='inventory.brand')),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_gpus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GPUs',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.gpu'),
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_operating_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Operating_Systems',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.operatingsystem'),
        ),
        migrations.CreateModel(
            name='DeviceSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=100)),
                ('spec_value', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='inventory.device')),
            ],
            options={
                'db_table': 'Device_Specs',
                'unique_together': {('device', 'spec_name')},
            },
        ),
    ]
