# Generated by Django 5.2.7 on 2026-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_device_in_transfer_accessory_in_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AddField(
            model_name='device',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
    ]
