# Generated by Django 5.2.7 on 2026-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_accessory_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
