# Generated by Django 5.2.7 on 2026-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_accessory_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
