# Generated by Django 5.2.7 on 2026-05-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_accessory_photo_device_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='device',
            name='photo',
        ),
    ]
