# Generated by Django 5.2.7 on 2026-05-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_photo_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'permissions': [('link_device_accessory', 'Can link or unlink an accessory to a device'), ('export_accessory', 'Can export accessory data to a file')]},
        ),
    ]
