# Generated by Django 6.0.4 on 2026-05-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_device_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'permissions': [('link_device_accessory', 'Can link or unlink an accessory to a device')]},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': [('retire_device', 'Can mark a device as Retired'), ('flag_device', 'Can change the status flag of a device'), ('toggle_maintenance', 'Can toggle maintenance mode on a device'), ('view_device_specs', 'Can view detailed hardware specifications'), ('export_device', 'Can export device data to a file'), ('view_history_device', 'Can view the assignment history of a device')]},
        ),
    ]
