# Generated by Django 5.2.7 on 2026-05-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_accessory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'permissions': [('export_accessory', 'Can export accessory data to a file')]},
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='device',
        ),
    ]
