# Generated by Django 6.0.4 on 2026-04-09 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredDeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('device_model_name', models.CharField(max_length=255)),
                ('cpu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gpu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hdd_storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('ssd_storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_size_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('screen_size_inch', models.FloatField(blank=True, null=True)),
                ('operating_system_name', models.CharField(blank=True, max_length=255, null=True)),
                ('governorate_name', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('ports_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_history', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_history', to='inventory.device')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_history', to='employees.employee')),
            ],
            options={
                'db_table': 'Delivered_Devices_History',
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField(blank=True, help_text='NULL = device still with employee', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_by', models.ForeignKey(db_column='Assigned_By', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.employee')),
            ],
            options={
                'db_table': 'Device_Assignments',
                'permissions': [('return_device', 'Can record that a device has been returned by an employee'), ('generate_report', 'Can export or print assignment reports')],
            },
        ),
        migrations.CreateModel(
            name='DeviceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.device')),
                ('from_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='locations.site')),
                ('to_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='locations.site')),
                ('transferred_by', models.ForeignKey(db_column='Transferred_By', on_delete=django.db.models.deletion.PROTECT, related_name='device_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Device_Transfers',
                'permissions': [('approve_transfer', 'Can approve a pending device site transfer')],
            },
        ),
    ]
