# Generated by Django 5.2.7 on 2026-05-01 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceassignment',
            name='returned_by',
            field=models.ForeignKey(blank=True, db_column='Returned_By', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
