# Generated by Django 5.2.7 on 2026-05-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_devicetransfer_status_accessorytransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetransfer',
            options={'permissions': [('approve_transfer', 'Can approve or reject a pending device site transfer'), ('export_transfer', 'Can export transfer records to a file')]},
        ),
    ]
