# Generated by Django 5.2.7 on 2026-05-05 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_add_returned_by'),
        ('employees', '0002_department_updated_by_employee_updated_by'),
        ('inventory', '0006_accessorytype_updated_by_brand_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField(blank=True, help_text='NULL = accessory still with employee', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_assignments', to='inventory.accessory')),
                ('assigned_by', models.ForeignKey(db_column='Assigned_By', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_accessories', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_assignments', to='employees.employee')),
                ('returned_by', models.ForeignKey(blank=True, db_column='Returned_By', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_accessories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Accessory_Assignments',
                'permissions': [('return_accessory', 'Can record that an accessory has been returned by an employee')],
            },
        ),
    ]
