# Generated by Django 6.0.4 on 2026-05-05 20:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_flag', models.CharField(blank=True, default='', help_text='Accessory flag before entering maintenance; restored on close', max_length=50)),
                ('issue_description', models.TextField()),
                ('maintenance_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External (Vendor)')], default='Internal', max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='inventory.accessory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_acc_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_acc_maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Accessory_Maintenance_Records',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_flag', models.CharField(blank=True, default='', help_text='Device flag before entering maintenance; restored on close', max_length=50)),
                ('issue_description', models.TextField()),
                ('maintenance_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External (Vendor)')], default='Internal', max_length=20)),
                ('vendor_name', models.CharField(blank=True, help_text='Fill if external maintenance', max_length=255, null=True)),
                ('sent_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField(blank=True, help_text='NULL = still under maintenance', null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='inventory.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Maintenance_Records',
                'permissions': [('close_maintenancerecord', 'Can close a maintenance record and add resolution notes'), ('view_cost', 'Can view the financial cost field on a maintenance record'), ('export_maintenancerecord', 'Can export maintenance records to a file')],
            },
        ),
    ]
