# Generated by Django 6.0.4 on 2026-05-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'permissions': [('close_maintenancerecord', 'Can close a maintenance record and add resolution notes'), ('view_cost', 'Can view the financial cost field on a maintenance record'), ('export_maintenancerecord', 'Can export maintenance records to a file')]},
        ),
    ]
