# Generated by Django 6.0.4 on 2026-04-09 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_governorates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Governorates',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, related_name='created_sites', to=settings.AUTH_USER_MODEL)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='locations.governorate')),
            ],
            options={
                'db_table': 'Sites',
            },
        ),
    ]
